# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  ps: Bootstrap

# Adapt as necessary starting from here

environment:
  global:
   WARNINGS_ARE_ERRORS: 0
   USE_RTOOLS: true

build_script:
  - R -e "install.packages('rJava', repos = 'http://cran.us.r-project.org', INSTALL_opts='--no-multiarch')"
  - R -e  "install.packages('devtools', repos = 'http://cran.us.r-project.org')"
  - R -e  "dir.create('C:/projects/javaonappveyortest/packrat/lib/i386-w64-mingw32/3.3.1', recursive = TRUE, mode = '777')"
  - R -e  "install.packages('rJava', repos = 'http://cran.us.r-project.org', lib = 'C:/projects/javaonappveyortest/packrat/lib/i386-w64-mingw32/3.3.1')"
  - R -e  "devtools::install_github('rstudio/packrat', lib = 'C:/projects/javaonappveyortest/packrat/lib/i386-w64-mingw32/3.3.1')" --args --bootstrap-packrat


test_script:
  - travis-tool.sh run_tests

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits
